name: Sample GitHub Action

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1002075@ds.study.iitm.ac.in
        run: echo "Hello, world!"
